version: '3.8'
services:
  root:
    image: othello-root:latest
    hostname: root
    container_name: othello-root
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - boardmodule
      - usermodule
      - mongo
  boardmodule:
    image: boardmodule:latest
    hostname: boardmodule
    container_name: boardmodule
    tty: true
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  usermodule:
    image: usermodule:latest
    hostname: usermodule
    container_name: usermodule
    tty: true
    ports:
      - "8082:8082"
    depends_on:
      - mongo
  mongo:
    image: othello-mongodb:latest
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
