version: '3.8'
services:
  root:
    image: othello-root:latest
    hostname: root
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - boardmodule
      - usermodule
  boardmodule:
    image: boardmodule:latest
    hostname: boardmodule
    tty: true
    ports:
      - "8081:8081"
  usermodule:
    image: usermodule:latest
    hostname: usermodule
    tty: true
    ports:
      - "8082:8082"
